// Backend-authoritative parity for the admin pricing form's live previews.
// __fixtures__/pricing-parity.json is generated by urgent-printers-backend/tests/pricing_parity_matrix.py
// (money is integer paise); every number the admin previews must equal what the backend charges/displays.
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { describe, it, expect } from 'vitest';
import {
  effectiveLimits, exampleText, formatQty, limitNotes, listingPreview, minOptionMultipliers, perPieceSuffix,
  tierForQuantity, unitPaiseWithMultipliers, cardPreviewText, pagePreviewText, type SaleState,
} from './orderQuantity';
import { formatPrice2 } from './formatPrice';

interface Opt { id: string; label: string; price_multiplier: number; is_active: boolean }
interface Tier { quantity: number; price_per_unit: number; mrp_per_unit?: number | null }
interface FxProduct {
  key: string;
  detail: { sizes: Opt[]; paper_types: Opt[]; finishes: Opt[]; sides_options: Opt[] };
  bounds: { min: number; max: number; stored_max: number | null; listing: number };
  admin: {
    window: 'none' | 'active' | 'scheduled' | 'expired';
    tiers: Tier[];
    specs: { sizes: Opt[]; paper_types: Opt[]; finishes: Opt[]; sides_options: Opt[] };
    limits: { listing: number | null; min: number | null; max: number | null };
    unit_label: string;
    listing: { qty: number; price: number | null; mrp: number | null; pct: number | null };
    examples: { q: number; total: number; mrp_total: number | null }[];
    below_lowest_unit: number | null;
  };
}
interface FxRow {
  p: string; q: number; k: string;
  o: { size_id: string | null; paper_id: string | null; finish_id: string | null; sides: string | null; ta: string | null };
  e?: { unit: number; mrp: number | null; tier: number; active: boolean };
}
const fx = JSON.parse(readFileSync(path.resolve(__dirname, '__fixtures__/pricing-parity.json'), 'utf8')) as {
  meta: { rows: number; products: number };
  products: FxProduct[];
  rows: FxRow[];
};

const money = (paise: number) => formatPrice2(paise / 100);
const groups = (p: FxProduct) => [p.admin.specs.sizes, p.admin.specs.paper_types, p.admin.specs.finishes, p.admin.specs.sides_options];
/** Window-inactive products with an MRP charge the MRP, which the admin form's preview does not model (handled via saleState). */
const windowClosedWithMrp = (p: FxProduct) =>
  (p.admin.window === 'scheduled' || p.admin.window === 'expired') && p.admin.tiers.some((t) => t.mrp_per_unit != null);
const comparable = fx.products;
const saleOf = (p: FxProduct): SaleState => (p.admin.window === 'scheduled' || p.admin.window === 'expired' ? p.admin.window : 'active');

describe('pricing-parity fixture', () => {
  it('is the large backend-generated matrix', () => {
    expect(fx.products.length).toBeGreaterThanOrEqual(50);
    expect(fx.rows.length).toBe(fx.meta.rows);
    expect(fx.rows.length).toBeGreaterThanOrEqual(2000);
  });
});

describe('admin effective limits equal the backend order_limits helpers', () => {
  it.each(fx.products.map((p) => p.key))('%s', (key) => {
    const p = fx.products.find((x) => x.key === key)!;
    const eff = effectiveLimits(p.admin.limits, p.admin.tiers);
    expect(eff.min).toBe(p.bounds.min);
    expect(eff.listing).toBe(p.bounds.listing);
    expect(eff.max).toBe(p.bounds.max);
    expect(eff.hasMax).toBe(p.bounds.stored_max !== null);
  });
});

describe('admin multiplier arithmetic and tier choice equal the backend for every matrix row', () => {
  it('per-piece price and MRP (exact decimal product, one HALF_UP rounding) and the tier chosen match', () => {
    const byKey = new Map(fx.products.map((p) => [p.key, p]));
    const bad: string[] = [];
    let compared = 0;
    for (const r of fx.rows) {
      if (!r.e) continue;
      const p = byKey.get(r.p)!;
      const find = (list: Opt[], ref: string | null) => (ref === null ? null : list.find((o) => o.id === ref || o.label === ref)!);
      const mults = [
        find(p.detail.sizes, r.o.size_id), find(p.detail.paper_types, r.o.paper_id),
        find(p.detail.finishes, r.o.finish_id), find(p.detail.sides_options, r.o.sides),
      ].filter((o): o is Opt => o !== null).map((o) => o.price_multiplier);
      const tier = tierForQuantity(p.admin.tiers, r.q)!;
      if (tier.quantity !== r.e.tier) bad.push(`${r.p} q=${r.q}: tier ${tier.quantity} vs ${r.e.tier}`);
      const closed = windowClosedWithMrp(p);
      const base = closed ? tier.mrp_per_unit ?? tier.price_per_unit : tier.price_per_unit;
      const unit = unitPaiseWithMultipliers(base, mults);
      if (unit !== r.e.unit) bad.push(`${r.p} q=${r.q} ${JSON.stringify(r.o)}: unit ${unit} vs ${r.e.unit}`);
      if (!closed && tier.mrp_per_unit != null) {
        const mrp = unitPaiseWithMultipliers(tier.mrp_per_unit, mults);
        const want = mrp > unit ? mrp : null;
        if (want !== r.e.mrp) bad.push(`${r.p} q=${r.q} ${JSON.stringify(r.o)}: mrp ${want} vs ${r.e.mrp}`);
      }
      compared++;
    }
    expect(compared).toBeGreaterThan(2000);
    expect(bad, bad.slice(0, 8).join('\n')).toEqual([]);
  });
});

describe('admin live preview ("Product card" / "Product page") equals the backend listing price', () => {
  it.each(comparable.map((p) => p.key))('%s', (key) => {
    const p = fx.products.find((x) => x.key === key)!;
    const eff = effectiveLimits(p.admin.limits, p.admin.tiers);
    const preview = listingPreview(p.admin.tiers, eff.listing, minOptionMultipliers(groups(p)), saleOf(p));
    const want = p.admin.listing;
    if (want.price === null) { expect(preview).toBeNull(); return; }
    expect(preview!.qty).toBe(want.qty);
    expect(preview!.totalPaise).toBe(want.price);
    expect(preview!.mrpTotalPaise).toBe(want.mrp);
    expect(preview!.percentOff).toBe(want.pct);
    expect(preview!.unitPaise * want.qty).toBe(want.price);
    const label = p.admin.unit_label;
    expect(cardPreviewText(preview!, label)).toBe(`${formatQty(want.qty, label)} for ${money(want.price)}`);
    expect(pagePreviewText(preview!, label, eff)).toContain(`total ${money(want.price)}`);
    expect(pagePreviewText(preview!, label, eff)).toContain(`${money(preview!.unitPaise)}${perPieceSuffix(label)}`);
  });
});

describe('admin "Example" column equals the backend line total for the tier', () => {
  it.each(comparable.map((p) => p.key))('%s', (key) => {
    const p = fx.products.find((x) => x.key === key)!;
    const label = p.admin.unit_label;
    for (const ex of p.admin.examples) {
      const tier = p.admin.tiers.find((t) => t.quantity === ex.q)!;
      const got = exampleText(tier.quantity, tier.price_per_unit, tier.mrp_per_unit, label);
      const want = `${formatQty(ex.q, label)} = ${money(ex.total)}` + (ex.mrp_total !== null ? ` (MRP ${money(ex.mrp_total)})` : '');
      expect(got, `${key} tier ${ex.q}`).toBe(want);
    }
  });
});

describe('admin limit notes agree with what the backend would charge', () => {
  it.each(comparable.map((p) => p.key))('%s', (key) => {
    const p = fx.products.find((x) => x.key === key)!;
    const eff = effectiveLimits(p.admin.limits, p.admin.tiers);
    const notes = limitNotes(p.admin.tiers, eff, p.admin.unit_label);
    const lowest = Math.min(...p.admin.tiers.map((t) => t.quantity));
    if (eff.min < lowest) {
      expect(p.admin.below_lowest_unit, 'backend charges the lowest tier below it').not.toBeNull();
      expect(notes.belowLowestTier).toContain(`${lowest.toLocaleString('en-IN')}+ rate (${money(p.admin.below_lowest_unit!)}${perPieceSuffix(p.admin.unit_label)})`);
    } else {
      expect(notes.belowLowestTier).toBeNull();
      expect(p.admin.below_lowest_unit).toBeNull();
    }
    const reachable = p.admin.tiers.filter((t) => t.quantity <= p.bounds.max);
    expect(notes.unreachableTiers.length).toBe(p.admin.tiers.length - reachable.length);
    const withMrp = p.admin.tiers.filter((t) => t.mrp_per_unit != null).length;
    expect(notes.mixedMrp).toBe(withMrp > 0 && withMrp < p.admin.tiers.length);
  });
});

describe('admin preview respects the discount window', () => {
  const closed = fx.products.filter(windowClosedWithMrp);

  it('the matrix contains scheduled and expired windows with MRPs', () => {
    expect(new Set(closed.map((p) => p.admin.window))).toEqual(new Set(['scheduled', 'expired']));
  });

  // Backend: outside [starts, ends) customers pay the MRP and the card shows no discount.
  it('Product card preview equals the backend listing price while the sale window is closed', () => {
    for (const p of closed) {
      const eff = effectiveLimits(p.admin.limits, p.admin.tiers);
      const preview = listingPreview(p.admin.tiers, eff.listing, minOptionMultipliers(groups(p)), saleOf(p));
      expect(preview!.totalPaise, `${p.key} (${p.admin.window})`).toBe(p.admin.listing.price);
    }
  });
});
