export const ROUTES = {
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  ORDERS: '/orders',
  ORDER_DETAIL: (id: string) => `/orders/${id}`,
  PRINTING_QUEUE: '/printing-queue',
  PRODUCTS: '/products',
  PRODUCT_NEW: '/products/new',
  PRODUCT_DETAIL: (id: string) => `/products/${id}`,
  CATEGORIES: '/categories',
  CATEGORY_DETAIL: (id: string) => `/categories/${id}`,
  CUSTOMERS: '/customers',
  CUSTOMER_DETAIL: (id: string) => `/customers/${id}`,
  PAYMENTS: '/payments',
  REFUNDS: '/payments/refunds',
  COUPONS: '/coupons',
  COUPON_DETAIL: (id: string) => `/coupons/${id}`,
  CONTENT_BANNERS: '/content/banners',
  CONTENT_TESTIMONIALS: '/content/testimonials',
  CONTENT_ANNOUNCEMENTS: '/content/announcements',
  CONTENT_FAQS: '/content/faqs',
  REVIEWS: '/reviews',
  SHIPPING: '/shipping',
  SHIPPING_SERVICEABILITY: '/shipping/serviceability',
  COMMUNICATIONS: '/communications',
  COMM_TEMPLATES: '/communications/templates',
  REPORTS_SALES: '/reports/sales',
  REPORTS_ORDERS: '/reports/orders',
  REPORTS_CUSTOMERS: '/reports/customers',
  REPORTS_OPERATIONS: '/reports/operations',
  STAFF: '/staff',
  ACTIVITY_LOG: '/staff/activity-log',
  STAFF_NOTIFICATIONS: '/staff/notifications',
  SETTINGS_GENERAL: '/settings/general',
  SETTINGS_OPERATIONS: '/settings/operations',
  SETTINGS_PAYMENTS: '/settings/payments',
  SETTINGS_NOTIFICATIONS: '/settings/notifications',
  SYSTEM: '/system',
} as const;
