// Hand-authored, not generated by the playwright-test MCP server's Generator agent — see
// pipeline/README.md's "Known infra findings" for why (the MCP server's internal test-server
// child process has a path-relativization bug that could not be resolved without repeated
// session restarts, which was declined after several attempts). Selectors below are grounded
// directly in the real source (CategoryForm.tsx, CategoriesTable.tsx, ConfirmDialog.tsx,
// the login page, MediaSection.tsx) rather than a live-DOM-validated agent run, so treat a
// first-run selector failure here as more plausible than it would be from a generated spec —
// fix the selector, don't loosen the assertion.
import { test, expect } from '../capture.js';

test.use({
  captureOptions: {
    feature: 'Category Management',
    plan: 'qa-pipeline/artifacts/plans/category-management-plan.json',
    axe: 'per-navigation',
    lighthouse: 'off', // kept off for this pass — CPU-conscious environment, not the happy-path's main goal
  },
});

test.describe('Category Management', () => {
  test('Create, edit, reorder, and delete a category', async ({ page, capture }) => {
    const uniqueName = `QA Pipeline Test Category ${Date.now()}`;

    // ── Auth (not part of the plan's step_ids — infrastructure to reach an authenticated page) ──
    await capture.step('auth-01', 'Open the login page', null, () => page.goto('/login'));
    await capture.type('auth-02', 'Enter the admin email', page.locator('#email'), 'admin@urgentprinters.com');
    await capture.type('auth-03', 'Enter the admin password', page.locator('#password'), 'SuperAdmin@123');
    await capture.step(
      'auth-04',
      'Submit the login form',
      page.getByRole('button', { name: 'Sign in' }),
      async (el) => {
        await el.click();
        await page.waitForURL('**/dashboard', { timeout: 15_000 });
      },
    );

    // ── hp-01: categories list ──
    await capture.step('hp-01', 'Open the categories list', null, () => page.goto('/categories'));
    await expect(page.getByRole('link', { name: 'Add Category' })).toBeVisible();

    // ── hp-02: Add Category ──
    await capture.step(
      'hp-02',
      'Click "Add Category"',
      page.getByRole('link', { name: 'Add Category' }),
      async (el) => {
        await el.click();
        await page.waitForURL('**/categories/new');
      },
    );
    await expect(page.getByText('New Category', { exact: true })).toBeVisible();

    // Name/Slug have no id/htmlFor association in the source (CategoryForm.tsx) — located via
    // the exact-text label's following sibling <input>, not getByLabel().
    const nameField = page.locator('label:text-is("Name *")').locator('xpath=following-sibling::input[1]');
    const slugField = page.locator('label:text-is("Slug *")').locator('xpath=following-sibling::input[1]');

    // ── hp-03: type Name ──
    await capture.type('hp-03', 'Enter the category name', nameField, uniqueName);

    // ── hp-04: observe auto-derived Slug ──
    await capture.step('hp-04', 'Observe the auto-derived Slug', slugField, async (el) => {
      await expect(el).not.toHaveValue('');
    });

    // ── hp-05: upload one image ──
    const imageInput = page.locator('input[type="file"][accept*="image"]');
    await capture.step('hp-05', 'Upload one category image', imageInput, async (el) => {
      await el.setInputFiles(
        'node_modules/@remotion/studio-server/web/coding-agent-icons/claude-code.png',
      );
      // Wait for the upload to finish (status line flips from "required" to "met").
      await expect(page.getByText(/Minimum of 1 photo met/)).toBeVisible({ timeout: 20_000 });
    });

    // ── hp-06: submit create ──
    // Scrolled into view *before* capture.step measures its bounding box — the form is tall
    // enough that this button sits below the fold otherwise, and the measurement happens
    // before fn() runs (i.e. before Playwright's own click-triggered auto-scroll).
    await page.getByRole('button', { name: 'Create Category' }).scrollIntoViewIfNeeded();
    await capture.step(
      'hp-06',
      'Submit the form',
      page.getByRole('button', { name: 'Create Category' }),
      async (el) => {
        await el.click();
        await expect(page.getByText('Category created')).toBeVisible({ timeout: 10_000 });
        await page.waitForURL('**/categories');
      },
    );

    // ── hp-07: locate the new row ──
    const newRow = page.locator('tr', { hasText: uniqueName });
    await capture.step('hp-07', 'Locate the new category row', newRow, async () => {
      await expect(newRow).toBeVisible();
      await expect(newRow.getByText('Active')).toBeVisible();
    });

    // ── hp-08: reorder — click Up arrow (first button in the Order column) ──
    const upArrow = newRow.locator('td').first().locator('button').first();
    await capture.step('hp-08', "Click the new row's Up arrow", upArrow, async (el) => {
      await el.click();
      // Reorder is fire-and-forget from the UI's perspective (no toast) — settle briefly.
      await page.waitForTimeout(500);
    });

    // ── hp-09: edit the category (open row menu -> Edit -> change Name -> Save), one plan step ──
    const editedName = `${uniqueName} (edited)`;
    const rowMenuTrigger = newRow.locator('button').last();
    await capture.step('hp-09', 'Edit the category: change its Name only', rowMenuTrigger, async (el) => {
      await el.click();
      await page.getByRole('menuitem', { name: 'Edit' }).click();
      await page.waitForURL('**/categories/*');
      await expect(page.getByText('Edit Category', { exact: true })).toBeVisible();

      const editNameField = page.locator('label:text-is("Name *")').locator('xpath=following-sibling::input[1]');
      await editNameField.fill('');
      await editNameField.fill(editedName);

      await page.getByRole('button', { name: 'Save Changes' }).click();
      await expect(page.getByText('Category updated')).toBeVisible({ timeout: 10_000 });
      await page.waitForURL('**/categories');
    });

    // ── hp-10: delete the category (open row menu -> Delete -> confirm), one plan step ──
    const editedRow = page.locator('tr', { hasText: editedName });
    await expect(editedRow).toBeVisible();
    const editedRowMenuTrigger = editedRow.locator('button').last();
    await capture.step('hp-10', 'Delete the category', editedRowMenuTrigger, async (el) => {
      await el.click();
      await page.getByRole('menuitem', { name: 'Delete' }).click();
      await expect(page.getByRole('dialog')).toBeVisible();

      await page.getByRole('button', { name: 'Delete Category' }).click();
      await expect(page.getByText(`"${editedName}" deleted`)).toBeVisible({ timeout: 10_000 });
      // The toast fires as soon as the DELETE request resolves, but the list is driven by a
      // separate invalidateQueries()-triggered refetch (useDeleteCategory, useCategories.ts) —
      // observed once to lag the toast by several seconds in a live run (server-side deletion
      // itself was confirmed immediate via a direct API check). This assertion belongs inside
      // the step specifically so a slow/failed refresh is recorded as a real run.json failure
      // instead of an untracked assertion outside any capture.step — see this feature's
      // analysis for how that first observation was investigated.
      await expect(page.locator('tr', { hasText: editedName })).toHaveCount(0, { timeout: 15_000 });
    });
  });
});
