// Hand-authored (Module 2 fallback), not generated by the playwright-test MCP server's
// Generator agent — see pipeline/README.md's "Known infra findings" #8: three orphaned
// `run-test-mcp-server` process trees were alive when this run started, which makes an MCP
// tool result indistinguishable from a stale-server artefact. Selectors below are grounded
// directly in the real source (ProductsTable.tsx, ProductForm/*.tsx, DataTable.tsx,
// ConfirmDialog.tsx, the login page) rather than a live-DOM-validated agent run, so treat a
// first-run selector failure here as more plausible than an app defect — fix the selector.
import { test, expect } from '../capture.js';
import { login, FIXTURES, nameField, slugField, shortDescField, categorySelect, imageInput, openSection } from './product-catalog.helpers';

test.use({
  captureOptions: {
    feature: 'Product Catalog Admin',
    plan: 'qa-pipeline/artifacts/plans/product-catalog-admin-to-storefront-plan.json',
    axe: 'per-navigation',
    lighthouse: 'off', // admin auth token is in-memory only — a Lighthouse checkpoint would land on /login
  },
});

test.describe('Product Catalog (Admin)', () => {
  test('Create, verify, edit, recategorise and archive a product', async ({ page, capture }) => {
    test.setTimeout(240_000);
    const productName = `QA Pipeline Test Product ${Date.now()}`;
    const editedShortDesc = 'Updated short description from the QA pipeline run.';

    await login(page, capture);

    // ── hp-01: product catalogue list ──
    await capture.step('hp-01', 'Open the product catalogue list', null, async () => {
      await page.goto('/products');
      await expect(page.getByRole('heading', { name: 'Products' })).toBeVisible();
      await expect(page.getByText('Manage your product catalogue.')).toBeVisible();
      await expect(page.getByRole('columnheader', { name: 'Product' })).toBeVisible();
      await expect(page.getByRole('columnheader', { name: 'From' })).toBeVisible();
    });

    // ── hp-02: Add Product ──
    const addProduct = page.getByRole('link', { name: 'Add Product' }).first();
    await capture.step('hp-02', "Click 'Add Product'", addProduct, async (el) => {
      await el.click();
      await page.waitForURL('**/products/new');
      await expect(page.getByRole('button', { name: 'Publish Product' })).toBeVisible();
    });

    // ── hp-03: product name (slug auto-derives) ──
    await capture.type('hp-03', 'Enter the product name', nameField(page), productName);
    await capture.step('hp-04', 'Observe the auto-derived Slug', slugField(page), async (el) => {
      await expect(el).toHaveValue(productName.toLowerCase().replace(/[^a-z0-9]+/g, '-'));
    });

    // ── hp-05: short description ──
    await capture.type(
      'hp-05',
      'Enter the short description',
      shortDescField(page),
      'Premium 350 GSM cards printed and dispatched within 24 hours.',
    );

    // ── hp-06: category ──
    await capture.step('hp-06', 'Select a category', categorySelect(page), async (el) => {
      // Categories load asynchronously — wait for the real option list before selecting.
      await expect(el.locator('option')).not.toHaveCount(1, { timeout: 15_000 });
      await el.selectOption({ label: 'Business Cards' });
      await expect(el).not.toHaveValue('');
    });

    // ── hp-07: three photos ──
    await capture.step('hp-07', 'Upload three product photos', imageInput(page), async (el) => {
      await expect(page.getByText('3 more photos required — minimum 3.')).toBeVisible();
      await el.setInputFiles([FIXTURES.front, FIXTURES.angle, FIXTURES.detail]);
      await expect(page.getByText('Minimum of 3 photos met (3/8).')).toBeVisible({ timeout: 60_000 });
    });

    // ── hp-08: default pricing tiers ──
    const firstTierQty = page.locator('input[name="pricing_tiers.0.quantity"]');
    await capture.step('hp-08', 'Review the default pricing tiers', firstTierQty, async (el) => {
      await expect(el).toHaveValue('100');
      await expect(page.locator('input[name^="pricing_tiers."][name$=".quantity"]')).toHaveCount(5);
      // Total column = quantity x price_per_unit through formatPrice (min 0 / max 2 fraction
      // digits), so 100 x 12.00 renders as '₹1,200', not '₹1,200.00'.
      await expect(page.getByText('₹1,200', { exact: true })).toBeVisible();
    });

    // ── hp-09: mark a tier as best value ──
    const bestValueStar = page.locator('button[title="Mark as best value"]').nth(3);
    await capture.step('hp-09', "Mark the 1,000-unit tier as 'Best Value'", bestValueStar, async (el) => {
      await el.click();
      await expect(el.locator('svg.fill-yellow-500')).toHaveCount(1);
      await expect(page.locator('button[title="Mark as best value"] svg.fill-yellow-500')).toHaveCount(1);
    });

    // ── hp-10: inventory tracking ──
    await capture.step('hp-10', 'Turn on inventory tracking and set stock levels', null, async () => {
      await openSection(page, 'Inventory');
      await page
        .locator('label', { hasText: 'Track inventory for this product' })
        .getByRole('switch')
        .click();
      await page.locator('input[name="stock_quantity"]').fill('500');
      await page.locator('input[name="low_stock_threshold"]').fill('50');
      await expect(page.getByText('500 units in stock.')).toBeVisible();
    });

    // ── hp-11: publish ──
    const publish = page.getByRole('button', { name: 'Publish Product' });
    await publish.scrollIntoViewIfNeeded();
    await capture.step('hp-11', "Click 'Publish Product'", publish, async (el) => {
      await el.click();
      await expect(page.getByText('Product created')).toBeVisible({ timeout: 30_000 });
      await page.waitForURL('**/products');
    });

    // ── hp-12: the new row ──
    const row = page.locator('tr', { hasText: productName });
    await capture.step('hp-12', 'Locate the new product row', row, async () => {
      await expect(row).toBeVisible({ timeout: 20_000 });
      await expect(row.getByText('Active', { exact: true })).toBeVisible();
      await expect(row.getByText('Business Cards')).toBeVisible();
      // 'From' column = Math.min(pricing_tiers.price_per_unit); the default tiers bottom out
      // at 4.20, which formatPrice renders as '₹4.2' (maximumFractionDigits: 2, no padding).
      await expect(row.getByText('₹4.2', { exact: true })).toBeVisible();
    });

    // ── hp-13: open for editing ──
    const rowMenu = row.locator('button').last();
    await capture.step('hp-13', "Open the row menu and click 'Edit'", rowMenu, async (el) => {
      await el.click();
      await page.getByRole('menuitem', { name: 'Edit' }).click();
      await page.waitForURL(/\/products\/\d+$/);
      await expect(page.getByRole('button', { name: 'Save Changes' })).toBeVisible({ timeout: 20_000 });
      await expect(nameField(page)).toHaveValue(productName);
    });

    // ── hp-14: edit the short description ──
    await capture.step('hp-14', 'Change the short description and save', shortDescField(page), async (el) => {
      await el.fill(editedShortDesc);
      await page.getByRole('button', { name: 'Save Changes' }).click();
      await expect(page.getByText('Product updated')).toBeVisible({ timeout: 30_000 });
    });

    // ── hp-15: reassign the category ──
    await capture.step('hp-15', 'Reassign the product to another category and save', categorySelect(page), async (el) => {
      await el.selectOption({ label: 'Posters' });
      await page.getByRole('button', { name: 'Save Changes' }).click();
      await expect(page.getByText('Product updated')).toBeVisible({ timeout: 30_000 });
      await page.goto('/products');
      await expect(page.locator('tr', { hasText: productName }).getByText('Posters')).toBeVisible({
        timeout: 20_000,
      });
    });

    // ── hp-16: archive from the row menu ──
    const archiveRow = page.locator('tr', { hasText: productName });
    const archiveMenu = archiveRow.locator('button').last();
    await capture.step('hp-16', 'Archive the product from the row menu', archiveMenu, async (el) => {
      await el.click();
      await page.getByRole('menuitem', { name: 'Delete' }).click();
      const dialog = page.getByRole('dialog');
      await expect(dialog).toBeVisible();
      await expect(dialog.getByText(`Archive "${productName}"?`)).toBeVisible();
      await expect(
        dialog.getByText(
          'The product will be archived and hidden from the storefront. It can be restored by changing its status back to Active.',
        ),
      ).toBeVisible();
      await page.getByRole('button', { name: 'Archive Product' }).click();
      await expect(page.getByText(`"${productName}" archived`)).toBeVisible({ timeout: 30_000 });
    });

    // ── hp-17: the archived product leaves the default (unfiltered) list view ──
    await capture.step('hp-17', 'Confirm the archived product no longer shows as Active', null, async () => {
      await page.reload();
      const archived = page.locator('tr', { hasText: productName });
      await expect(archived.getByText('Active', { exact: true })).toHaveCount(0, { timeout: 20_000 });
    });
  });
});
